package com.antiprocrastinacion.lock

object MotivationalPhrases {
    val PHRASES = listOf(
        "✨ Tu mente es para tener ideas, no para guardarlas. Anótalas en tus notas.",
        "🌿 La disciplina de hoy es la tranquilidad de tu futuro.",
        "💡 Si una idea cruza tu mente, anótala en tus notas y sigue enfocado.",
        "🧠 Pensar por ti mismo es el superpoder más valioso que tienes.",
        "🎯 Cada minuto de enfoque te acerca a la versión que quieres ser.",
        "🕊️ Libera la carga mental escribiendo lo que sientes en tus notas.",
        "⚡ La procrastinación es la ladrona del potencial. Tú tienes el control.",
        "🧘 El silencio y la concentración son el hábitat de los grandes logros.",
        "📜 Todo gran proyecto comenzó como una simple nota anotada a tiempo.",
        "🌌 Tu atención es tu activo más valioso. No se la regales a las redes.",
        "🎨 Escribir lo que piensas te aclara la mente y te devuelve el enfoque.",
        "🌊 La constancia supera al talento cuando el talento no se esfuerza.",
        "✨ No aplaces lo que puedes avanzar en este preciso instante.",
        "🌿 Tu futuro yo te agradecerá los 60 minutos de enfoque de hoy.",
        "💡 Deja que las distracciones pasen como nubes y mantén el rumbo.",
        "🧠 Cuestiona tus impulsos antes de ceder a la tentación de distreerte.",
        "🎯 El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
        "🕊️ Vaciando tu cabeza en notas le das espacio a nuevas ideas brillantes.",
        "⚡ Tienes la capacidad y la energía para terminar lo que empezaste.",
        "🧘 Respira hondo, retoma tu objetivo y confía en tu proceso.",
        "📜 Una nota escrita vale más que mil intenciones olvidadas.",
        "🌌 Tu tiempo es limitado, no lo malgastes viviendo la vida de otros.",
        "🎨 El arte de avanzar consiste en empezar sin buscar la perfección.",
        "🌊 La paz mental llega cuando cumples los compromisos contigo mismo.",
        "✨ El enfoque no es privación, es libertad para construir lo que amas.",
        "🌿 Ningún obstáculo es más grande que tu determinación.",
        "💡 Si te viene un pendiente a la cabeza, descárgalo en tus notas.",
        "🧠 Cultiva el criterio propio antes de consumir opiniones ajenas.",
        "🎯 Mantente firme en tu meta, aunque el camino requiera paciencia.",
        "🕊️ La claridad mental comienza cuando organizas tus pensamientos.",
        "⚡ Tu fuerza de voluntad se fortalece cada vez que resistes una distracción.",
        "🧘 Encuentra serenidad en la tarea que tienes justo enfrente.",
        "📜 Escribir tus pendientes te libera del estrés de recordarlo todo.",
        "🌌 No te compares con los demás, compárate con quien eras ayer.",
        "🎨 Crea el hábito de anotar todo lo importante y verás la diferencia.",
        "🌊 La autodisciplina es la máxima expresión de amor propio.",
        "✨ Lo único que se interpone entre tú y tu meta es la acción.",
        "🌿 Hoy es un excelente día para demostrarte de lo que eres capaz.",
        "💡 Transforma tus pensamientos dispersos en notas organizadas.",
        "🧠 Reflexiona sobre tus prioridades antes de reaccionar al entorno.",
        "🎯 Domina tu atención y dominarás los resultados de tu vida.",
        "🕊️ Apuntar una idea te permite soltarla y volver al presente.",
        "⚡ Cada decisión de no distraerte es un triunfo sobre la inercia.",
        "🧘 El estado de flujo ocurre cuando te entregas al 100% al momento.",
        "📜 Las notas son el mapa mental para ordenar tus grandes metas.",
        "🌌 Mantén la calma, confía en tu esfuerzo y sigue adelante.",
        "🎨 La inspiración te encontrará trabajando, no esperando.",
        "🌊 Construye tu disciplina bloque a bloque, minuto a minuto.",
        "✨ El esfuerzo silencioso produce resultados estruendosos.",
        "🌿 Prioriza lo que verdaderamente importa en tu vida.",
        "💡 Tu bloc de notas es tu aliado para proteger tu concentración.",
        "🧠 Apagar el ruido externo te permite escuchar tu propia voz.",
        "🎯 Mantén los ojos en la meta y los pies en la acción.",
        "🕊️ Escribir aclara las ideas oscuras y potencia las brillantes.",
        "⚡ No esperes a tener ganas, la motivación aparece al actuar.",
        "🧘 Cultiva el enfoque como un músculo que entrenas cada día.",
        "📜 Regístralo en tus notas para que no se pierda en el olvido.",
        "🌌 Sé el arquitecto de tu propia atención y de tu tiempo.",
        "🎨 Pequeños progresos diarios generan transformaciones gigantes.",
        "🌊 El control de tu destino empieza con el control de tus minutos.",
        "✨ El tiempo bien invertido nunca es tiempo perdido.",
        "🌿 Rompe el ciclo de la procrastinación con una sola acción concreta.",
        "💡 Tu bloc de notas está siempre disponible para vaciar la mente.",
        "🧠 Pensar con profundidad requiere desconectarse del ruido.",
        "🎯 La perseverancia es la clave que abre todas las puertas.",
        "🕊️ Descarga tu mente en notas y siente el alivio inmediato.",
        "⚡ Haz que este bloque de tiempo valga la pena.",
        "🧘 La tranquilidad es el resultado de saber que estás avanzando.",
        "📜 Un recordatorio anotado a tiempo evita mil distracciones.",
        "🌌 Tu verdadero potencial se revela cuando te concentras de verdad.",
        "🎨 Da lo mejor de ti en lo que estás haciendo en este instante.",
        "🌊 La constancia no es suerte, es una elección diaria.",
        "✨ Hoy estás construyendo el camino por el que caminarás mañana.",
        "🌿 Cierra las pestañas innecesarias y enfócate en lo esencial.",
        "💡 Si surge una idea creativa, asegúrala en tus notas.",
        "🧠 La libertad mental se gana eligiendo a qué le pones atención.",
        "🎯 Céntrate en el proceso y los resultados llegarán solos.",
        "🕊️ Escribir ayuda a procesar emociones e ideas con claridad.",
        "⚡ Eres más fuerte de lo que crees y más capaz de lo que imaginas.",
        "🧘 Enfócate en una sola cosa a la vez y verás la magia.",
        "📜 Las buenas ideas se esfuman si no las capturas en notas.",
        "🌌 El valor del tiempo se mide en la calidad de tu atención.",
        "🎨 Confía en tu talento y respalda ese talento con disciplina.",
        "🌊 La serenidad interior nace del compromiso con tus metas.",
        "✨ No permitas que lo urgente aplaste a lo verdaderamente importante.",
        "🌿 Haz de la concentración tu mejor hábito diario.",
        "💡 Utiliza las notas para estructurar tus pensamientos con paz.",
        "🧠 Fomenta tu curiosidad y piensa de forma independiente.",
        "🎯 Visualiza tu objetivo cumplido y sigue avanzando.",
        "🕊️ Un pensamiento escrito en notas deja de atormentar tu mente.",
        "⚡ Vence la inercia del teléfono y toma el control de tu vida.",
        "🧘 Dedícale tu atención plena a lo que tienes entre manos.",
        "📜 Guarda tus descubrimientos en notas y revísalos más tarde.",
        "🌌 El mundo pertenece a quienes dominan su propia atención.",
        "🎨 Cada minuto de enfoque es un voto por la persona que deseas ser.",
        "🌊 Las grandes obras son la suma de horas de trabajo enfocado.",
        "✨ Reemplaza el impulso de navegar sin rumbo por un momento de reflexión.",
        "🌿 Sigue adelante, estás más cerca de lo que estabas al empezar.",
        "💡 Anota tus inquietudes en notas y vuelve a trabajar en calma.",
        "🧠 Pensar bien requiere tiempo y espacio sin interrupciones.",
        "🎯 La disciplina te llevará a donde la motivación no alcanza.",
        "🕊️ Escribir es la mejor medicina contra la saturación mental.",
        "⚡ Haz que tu tiempo trabaje a tu favor, no en tu contra.",
        "🧘 El momento perfecto para concentrarte es ahora mismo.",
        "📜 Guarda cada aprendizaje importante en tu bloc de notas.",
        "🌌 Dirige tu energía mental hacia lo que construyes, no hacia el ruido.",
        "🎨 Trabaja duro en silencio y deja que tus frutos hablen por ti.",
        "🌊 El hábito del enfoque te abrirá puertas insospechadas.",
        "✨ Valorar tu tiempo es valorar tu propia existencia.",
        "🌿 Di que no a lo efímero para poder decirle que sí a lo importante.",
        "💡 Haz de tu bloc de notas un refugio de claridad y orden.",
        "🧠 Tu mente es libre cuando decides activamente en qué pensar.",
        "🎯 Un paso a la vez, mantén la vista en tu horizonte.",
        "🕊️ Libérate de la presión de recordar todo: usa tus notas.",
        "⚡ Toma el mando de tus decisiones y avanza sin vacilar.",
        "🧘 Sumérgete en el presente y disfruta del trabajo bien hecho.",
        "📜 Tus notas son el cimiento de tu productividad diaria.",
        "🌌 La grandeza se cultiva en los momentos de aislamiento enfocado.",
        "🎨 Ponle alma y presencia a lo que estés haciendo hoy.",
        "🌊 La constancia vence a la procrastinación siempre.",
        "✨ Cada pequeño esfuerzo sostenido produce grandes frutos.",
        "🌿 Cuida tu energía mental evitando el consumo pasivo.",
        "💡 Ten a mano tus notas para capturar la chispa de la inspiración.",
        "🧠 Cuestiona el hábito de mirar el celular sin necesidad.",
        "🎯 Alcanzar tus metas es cuestión de perseverancia enfocada.",
        "🕊️ Saca lo que tienes dentro y escríbelo en tus notas.",
        "⚡ Tu capacidad de enfoque es tu ventaja competitiva.",
        "🧘 Haz una pausa, respira, revisa tus notas y continúa.",
        "📜 Organizar tus notas es organizar tu propio futuro.",
        "🌌 La verdadera maestría exige horas de práctica concentrada.",
        "🎨 Pinta tu día con la satisfacción de haber estado presente.",
        "🌊 Mantén la disciplina y cosecha la tranquilidad.",
        "✨ El enfoque sostenido cambia vidas.",
        "🌿 Sé paciente contigo y constante con tus acciones.",
        "💡 Las notas claras generan acciones eficientes.",
        "🧠 Aprende a disfrutar del silencio reflexivo.",
        "🎯 Tu destino lo moldeas con las elecciones de cada hora.",
        "🕊️ Escribe para comprender, lee para aprender, enfócate para crear.",
        "⚡ Supera los pretextos y ponte en marcha.",
        "🧘 Conéctate con el propósito de lo que haces hoy.",
        "📜 Deja constancia de tus mejores ideas en notas.",
        "🌌 La magia ocurre fuera de la zona de distracción.",
        "🎨 El enfoque es la luz que ilumina tu creatividad.",
        "🌊 Sigue construyendo con firmeza y serenidad.",
        "✨ Recuerda por qué empezaste y sigue hasta el final.",
        "🌿 Tu atención vale oro: regálasela a tus sueños.",
        "💡 Descarga tus ideas en notas y mantén tu paz mental.",
        "🧠 Pensar por ti mismo te hace verdaderamente libre.",
        "🎯 Domina la paciencia y los resultados hablarán por sí solos.",
        "📜 La constancia silenciosa genera transformaciones extraordinarias."
    )

    fun getRandomPhrase(): String {
        return PHRASES.random()
    }
}
